let hostingFaq = document.getElementById("hostingFaq");
let hostingFaqBtn = document.getElementById("hostingFaqBtn");
let offeringFaq = document.getElementById("offeringFaq");
let offeringFaqBtn = document.getElementById("offeringFaqBtn");
let serviceFaq = document.getElementById("serviceFaq");
let serviceFaqBtn = document.getElementById("serviceFaqBtn");
let profileFaq = document.getElementById("profileFaq");
let profileFaqBtn = document.getElementById("profileFaqBtn");
let friendsFaq = document.getElementById("friendsFaq");
let friendsFaqBtn = document.getElementById("friendsFaqBtn");
let requestFaq = document.getElementById("requestFaq");
let requestFaqBtn = document.getElementById("requestFaqBtn");
let generalFaq = document.getElementById("generalFaq");
let generalFaqBtn = document.getElementById("generalFaqBtn");
let generalImg = document.getElementById("generalImg");
let hostingImg = document.getElementById("hostingImg");
let offeringImg = document.getElementById("offeringImg");
let serviceImg = document.getElementById("serviceImg");
let profileImg = document.getElementById("profileImg");
let friendsImg = document.getElementById("friendsImg");
let requestImg = document.getElementById("requestImg");

let hosting = () => {
    hostingFaq.style.display = "block";
    hostingFaqBtn.classList.add("faqBtnActive");
    offeringFaq.style.display = "none";
    offeringFaqBtn.classList.remove("faqBtnActive");
    serviceFaq.style.display = "none";
    serviceFaqBtn.classList.remove("faqBtnActive");
    profileFaq.style.display = "none";
    profileFaqBtn.classList.remove("faqBtnActive");
    friendsFaq.style.display = "none";
    friendsFaqBtn.classList.remove("faqBtnActive");
    requestFaq.style.display = "none";
    requestFaqBtn.classList.remove("faqBtnActive");
    generalFaq.style.display = "none";
    generalFaqBtn.classList.remove("faqBtnActive");
    generalImg.src='./assets/faqGeneral.png';
    hostingImg.src='./assets/faqHostingColor.png';
    offeringImg.src='./assets/faqOffering.png';
    serviceImg.src='./assets/faqServices.png';
    profileImg.src='./assets/faqProfile.png';
    friendsImg.src='./assets/faqFriends.png';
    requestImg.src='./assets/faqRequest.png';
}

let ofering = () => {
    hostingFaq.style.display = "none";
    hostingFaqBtn.classList.remove("faqBtnActive");
    offeringFaq.style.display = "block";
    offeringFaqBtn.classList.add("faqBtnActive");
    serviceFaq.style.display = "none";
    serviceFaqBtn.classList.remove("faqBtnActive");
    profileFaq.style.display = "none";
    profileFaqBtn.classList.remove("faqBtnActive");
    friendsFaq.style.display = "none";
    friendsFaqBtn.classList.remove("faqBtnActive");
    requestFaq.style.display = "none";
    requestFaqBtn.classList.remove("faqBtnActive");
    generalFaq.style.display = "none";
    generalFaqBtn.classList.remove("faqBtnActive");
    generalImg.src='./assets/faqGeneral.png';
    hostingImg.src='./assets/faqHosting.png';
    offeringImg.src='./assets/faqOfferingColor.png';
    serviceImg.src='./assets/faqServices.png';
    profileImg.src='./assets/faqProfile.png';
    friendsImg.src='./assets/faqFriends.png';
    requestImg.src='./assets/faqRequest.png';
}
let service = () => {
    hostingFaq.style.display = "none";
    hostingFaqBtn.classList.remove("faqBtnActive");
    offeringFaq.style.display = "none";
    offeringFaqBtn.classList.remove("faqBtnActive");
    serviceFaq.style.display = "block";
    serviceFaqBtn.classList.add("faqBtnActive");
    profileFaq.style.display = "none";
    profileFaqBtn.classList.remove("faqBtnActive");
    friendsFaq.style.display = "none";
    friendsFaqBtn.classList.remove("faqBtnActive");
    requestFaq.style.display = "none";
    requestFaqBtn.classList.remove("faqBtnActive");
    generalFaq.style.display = "none";
    generalFaqBtn.classList.remove("faqBtnActive");
    generalImg.src='./assets/faqGeneral.png';
    hostingImg.src='./assets/faqHosting.png';
    offeringImg.src='./assets/faqOffering.png';
    serviceImg.src='./assets/faqServicesColor.png';
    profileImg.src='./assets/faqProfile.png';
    friendsImg.src='./assets/faqFriends.png';
    requestImg.src='./assets/faqRequest.png';
}
let profile = () => {
    hostingFaq.style.display = "none";
    hostingFaqBtn.classList.remove("faqBtnActive");
    offeringFaq.style.display = "none";
    offeringFaqBtn.classList.remove("faqBtnActive");
    serviceFaq.style.display = "none";
    serviceFaqBtn.classList.remove("faqBtnActive");
    profileFaq.style.display = "block";
    profileFaqBtn.classList.add("faqBtnActive");
    friendsFaq.style.display = "none";
    friendsFaqBtn.classList.remove("faqBtnActive");
    requestFaq.style.display = "none";
    requestFaqBtn.classList.remove("faqBtnActive");
    generalFaq.style.display = "none";
    generalFaqBtn.classList.remove("faqBtnActive");
    generalImg.src='./assets/faqGeneral.png';
    hostingImg.src='./assets/faqHosting.png';
    offeringImg.src='./assets/faqOffering.png';
    serviceImg.src='./assets/faqServices.png';
    profileImg.src='./assets/faqProfileColor.png';
    friendsImg.src='./assets/faqFriends.png';
    requestImg.src='./assets/faqRequest.png';
}
let friends = () => {
    hostingFaq.style.display = "none";
    hostingFaqBtn.classList.remove("faqBtnActive");
    offeringFaq.style.display = "none";
    offeringFaqBtn.classList.remove("faqBtnActive");
    serviceFaq.style.display = "none";
    serviceFaqBtn.classList.remove("faqBtnActive");
    profileFaq.style.display = "none";
    profileFaqBtn.classList.remove("faqBtnActive");
    friendsFaq.style.display = "block";
    friendsFaqBtn.classList.add("faqBtnActive");
    requestFaq.style.display = "none";
    requestFaqBtn.classList.remove("faqBtnActive");
    generalFaq.style.display = "none";
    generalFaqBtn.classList.remove("faqBtnActive");
    generalImg.src='./assets/faqGeneral.png';
    hostingImg.src='./assets/faqHosting.png';
    offeringImg.src='./assets/faqOffering.png';
    serviceImg.src='./assets/faqServices.png';
    profileImg.src='./assets/faqProfile.png';
    friendsImg.src='./assets/faqFriendsColor.png';
    requestImg.src='./assets/faqRequest.png';
}
let request = () => {
    hostingFaq.style.display = "none";
    hostingFaqBtn.classList.remove("faqBtnActive");
    offeringFaq.style.display = "none";
    offeringFaqBtn.classList.remove("faqBtnActive");
    serviceFaq.style.display = "none";
    serviceFaqBtn.classList.remove("faqBtnActive");
    profileFaq.style.display = "none";
    profileFaqBtn.classList.remove("faqBtnActive");
    friendsFaq.style.display = "none";
    friendsFaqBtn.classList.remove("faqBtnActive");
    requestFaq.style.display = "block";
    requestFaqBtn.classList.add("faqBtnActive");
    generalFaq.style.display = "none";
    generalFaqBtn.classList.remove("faqBtnActive");
    generalImg.src='./assets/faqGeneral.png';
    hostingImg.src='./assets/faqHosting.png';
    offeringImg.src='./assets/faqOffering.png';
    serviceImg.src='./assets/faqServices.png';
    profileImg.src='./assets/faqProfile.png';
    friendsImg.src='./assets/faqFriends.png';
    requestImg.src='./assets/faqRequestColor.png';
}
let general = () => {
    hostingFaq.style.display = "none";
    hostingFaqBtn.classList.remove("faqBtnActive");
    offeringFaq.style.display = "none";
    offeringFaqBtn.classList.remove("faqBtnActive");
    serviceFaq.style.display = "none";
    serviceFaqBtn.classList.remove("faqBtnActive");
    profileFaq.style.display = "none";
    profileFaqBtn.classList.remove("faqBtnActive");
    friendsFaq.style.display = "none";
    friendsFaqBtn.classList.remove("faqBtnActive");
    requestFaq.style.display = "none";
    requestFaqBtn.classList.remove("faqBtnActive");
    generalFaq.style.display = "block";
    generalFaqBtn.classList.add("faqBtnActive");
    generalImg.src='./assets/faqHostingColor.png';
    hostingImg.src='./assets/faqHosting.png';
    offeringImg.src='./assets/faqOffering.png';
    serviceImg.src='./assets/faqServices.png';
    profileImg.src='./assets/faqProfile.png';
    friendsImg.src='./assets/faqFriends.png';
    requestImg.src='./assets/faqRequest.png';
}
general();